POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/bhargav/yocto-imx6ull/poky/meta \
  /home/bhargav/yocto-imx6ull/poky/meta-poky \
  /home/bhargav/yocto-imx6ull/poky/meta-yocto-bsp \
  /home/bhargav/yocto-imx6ull/meta-openembedded/meta-oe \
  /home/bhargav/yocto-imx6ull/meta-openembedded/meta-python \
  /home/bhargav/yocto-imx6ull/meta-openembedded/meta-networking \
  /home/bhargav/yocto-imx6ull/meta-freescale \
  /home/bhargav/yocto-imx6ull/meta-qt5 \
  /home/bhargav/yocto-imx6ull/meta-swupdate \
  /home/bhargav/yocto-imx6ull/meta-custom-hmi \
"
