CONF_VERSION = "2"

# Machine & Init Configuration
MACHINE = "imx6ullevk"
KERNEL_DEVICETREE = "okmx6ull-c-emmc.dtb imx6ull-custom-hmi.dtb imx6ull-14x14-evk.dtb"
DISTRO = "poky"
INIT_MANAGER = "systemd"
SERIAL_CONSOLES = "115200;ttymxc0 115200;ttymxc5"
WKS_FILE = "imx-sdcard-ab.wks"

IMX_DEFAULT_BSP = "nxp"
DISTRO_FEATURES:append = " wayland pam opengl"
HOSTTOOLS += "cmake"





IMAGE_BOOT_FILES:append = " \
    okmx6ull-c-emmc.dtb \
    imx6ull-custom-hmi.dtb \
    okmx6ull-c-emmc.dtb;imx6ull-14x14-evk.dtb \
    boot.scr \
    splash.bmp \
    logo.bmp \
"
EXTRA_IMAGEDEPENDS += "u-boot-script"


EXTRA_IMAGE_FEATURES ?= "debug-tweaks"


# Performance tuning for 6-core Intel i5 CPU
BB_NUMBER_THREADS = "6"
PARALLEL_MAKE = "-j 6"

# Qt 5.15 LTS version
PREFERRED_VERSION_qtbase = "5.15%"
PREFERRED_VERSION_qtdeclarative = "5.15%"
PREFERRED_VERSION_qtquickcontrols2 = "5.15%"

# Include Qt 5.15.2, libgpiod, SWUpdate, and Qt5 Cinematic Experience demo
IMAGE_INSTALL:append = " \
    qtbase \
    qtbase-plugins \
    qtdeclarative \
    qtquickcontrols2 \
    libgpiod \
    libgpiod-tools \
    libgpiod-dev \
    avahi-autoipd \
    swupdate \
    cinematicexperience \
"

# Package management & Licensing
LICENSE_FLAGS_ACCEPTED = "commercial"
PACKAGECONFIG:append:pn-qtbase = " linuxfb gsl eglfs tslib"

# Automatically remove intermediate work files to save disk space
INHERIT += "rm_work"

# Accept Freescale EULA
ACCEPT_FSL_EULA = "1"

