#!/bin/sh
### BEGIN INIT INFO
# Provides:          hmi-app
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Fast-Boot Custom Qt 5.15 HMI Desktop Application
### END INIT INFO

export QT_QPA_PLATFORM=linuxfb:fb=/dev/fb0
export QT_QPA_GENERIC_PLUGINS=evdevtouch:/dev/input/touchscreen0
export QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS=/dev/input/touchscreen0
export QT_QPA_FB_NO_LIBINPUT=1

DAEMON=/usr/bin/hmi-app
NAME=hmi-app
DESC="Qt 5.15 HMI Desktop"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon -S -b -m -p /var/run/$NAME.pid -x $DAEMON
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon -K -p /var/run/$NAME.pid
    echo "$NAME."
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
